version: '3'
services:
  sftp:
    image: "emberstack/sftp:build-5.1.72"
    ports:
      - "2200:22"
    volumes:
      - ./config/sftp.config.json:/app/config/sftp.json:ro
#      - ./data/demo/object_engine:/home/demo/sftp/object_engine
#      - ./data/demo/object_engine_processed:/home/demo/sftp/object_engine_processed
#      - ./data/demo/object_engine_failed:/home/demo/sftp/object_engine_failed
#      - ./data/demo/object_engine_reject:/home/demo/sftp/object_engine_reject
#    entrypoint: ["/bin/sh", "-c", "chown -R 1000:1000 /home/demo/sftp && chmod -R 755 /home/demo/sftp && tini -- dotnet ES.SFTP.dll"]
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 600 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
