version: '3'
services:
  sftp:
    image: "emberstack/sftp:build-5.1.72"
    ports:
      - "2200:22"
    volumes:
      - ./config/sftp.config.json:/app/config/sftp.json:ro
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 600 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
